{{- if .Values.seerr.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.config.storageClass }}
  resources:
    requests:
      storage: {{ .Values.seerr.configSize }}
{{- end }}