{{- if .Values.flaresolverr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: flaresolverr
  ports:
    - port: {{ .Values.flaresolverr.port }}
      targetPort: {{ .Values.flaresolverr.port }}
{{- end }}