apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-scripts
  namespace: {{ .Release.Namespace }}
data:
  port-update.sh: |
  {{ (.Files.Glob "gluetun-scripts/port-update.sh").AsConfig | indent 2 }}