apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-scripts
  namespace: {{ .Release.Namespace }}
data:
  port-update.sh: |-
{{ (.Files.Get "gluetun-scripts/port-update.sh").AsConfig | indent 4 }}