{{- if .Values.qbittorrent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: {{ .Release.Namespace }}
  labels:
    app: qbittorrent
spec:
  template:
    spec:

      containers:

      - name: gluetun
        image: qmcgaw/gluetun:latest

        securityContext:
          capabilities:
            add:
              - NET_ADMIN

        env:
          - name: VPN_SERVICE_PROVIDER
            value: custom

          - name: VPN_TYPE
            value: wireguard

          - name: FIREWALL
            value: "on"

          - name: TZ
            value: Europe/Paris

        volumeMounts:
          - name: vpn
            mountPath: /gluetun/wireguard
            readOnly: true

      - name: qbittorrent

        image: ghcr.io/hotio/qbittorrent:latest
        env:
          - name: PUID
            value: {{ .Values.global.puid | quote }}
          - name: PGID
            value: {{ .Values.global.pgid | quote }}
          - name: UMASK
            value: {{ .Values.global.umask | quote }}
          - name: TZ
            value: {{ .Values.global.timezone | quote }}
          - name: WEBUI_PORT
            value: "8080"

        ports:
          - containerPort: 8080
          - containerPort: 6881
            protocol: TCP
          - containerPort: 6881
            protocol: UDP

        volumeMounts:
          - name: config
            mountPath: /config

          - name: nas
            mountPath: /downloads

      volumes:

      - name: vpn
        secret:
          secretName: qbittorrent-wireguard-conf

      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-config

      - name: nas
        persistentVolumeClaim:
          claimName: nas-data
{{- end }}
