{{- if .Values.qbittorrent.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - {{ .Values.ingress.entrypoint }}
  routes:
    - match: "Host(`{{ .Values.qbittorrent.host }}`)"
      kind: Rule
      services:
        - name: qbittorrent
          port: 8080
  tls:
    secretName: iliesflix-tls
{{- end }}
