# templates/qbittorrent/externalsecret.yaml
{{- if .Values.qbittorrent.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wireguard-private-key
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.qbittorrent.vpnSecret }}
    creationPolicy: Owner
  data:
    - secretKey: wireguard-private-key
      remoteRef:
        key: qbittorrent-vpn-key
{{- end }}