apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-ibenyahia-fr
  namespace: default
spec:
  secretName: wildcard-exemple-com-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: "*.exemple.com"
  dnsNames:
    - "exemple.com"
    - "*.exemple.com"