{{- if .Values.rustatio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustatio-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.config.storageClass }}
  resources:
    requests:
      storage: {{ .Values.rustatio.configSize }}
{{- end }}
 
