apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-web
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`argocd.spiderman.lan`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443