apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # LAN (HTTP)
    - kind: Rule
      match: Host(`argocd.spiderman.lan`)
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.spiderman.lan`) && Header(`Content-Type`, `application/grpc`)
      services:
        - name: argocd-server
          port: 80
          scheme: h2c

    # Public (HTTPS)
    - kind: Rule
      match: Host(`argocd.ibenyahia.fr`)
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.ibenyahia.fr`) && Header(`Content-Type`, `application/grpc`)
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-tls