apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyswarm
  namespace: {{ .Release.Namespace }}
  labels:
    app: jellyswarm
    app.kubernetes.io/part-of: iliesflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyswarm
  template:
    metadata:
      labels:
        app: jellyswarm
    spec:
      containers:
        - name: jellyswarm
          image: ghcr.io/llukas22/jellyswarrm:latest
          env:
            - name: JELLYSWARRM_USERNAME
              value: admin
            - name: JELLYSWARRM_PASSWORD
              value: jellyswarm
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: iliesflix-jellyswarm-data
