apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iliesflix-jellyswarm-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi

