apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketid-nas-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
