apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketid-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 1Gi
