{{- if .Values.profilarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: profilarr
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: profilarr
  ports:
    - name: http
      port: 6868
      targetPort: 6868
{{- end }}