apiVersion: v2
name: paperless
description: My own paperless chart
type: application
version: 0.1.0
keywords:
  - paperasse
  - administratif
  - relou
  - avis-dimpots
  - enfintacompris
maintainers:
  - name: ilies
