apiVersion: v2
name: argocd
description: My personnal helm chart for argocd
type: application
version: 0.1.1
appVersion: "v3.4.3"
dependencies:
- name: argo-cd
  alias: argocd
  version: "9.5.21"
  repository: "https://argoproj.github.io/argo-helm"