apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    ports: 
      minecraft:
        port: 25565
        expose:
          default: true
        exposedPort: 25565
        protocol: TCP
      websecure-pub:
        port: 8443
        expose:
          default: true
        exposedPort: 8443
        protocol: TCP
        tls:
          enabled: true
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.ibenyahia.fr`)
        entryPoints: 
          - web
          - websecure