apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: satisfactory-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: satisfactory-tls
  dnsNames:
    - satisfactory.ibenyahia.fr 
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer