{{- if .Values.joal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joal
  namespace: {{ .Release.Namespace }}
  labels:
    app: joal
    app.kubernetes.io/part-of: iliesflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joal
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: joal
    spec:
      containers:
        - name: joal
          image: {{ .Values.joal.image }}
          args:
            - "--joal-conf=/data"
            - "--spring.main.web-environment=true"
            - "--server.port=80"
            - "--joal.ui.path.prefix={{ .Values.joal.uiPathPrefix }}"
            - "--joal.ui.secret-token=$(JOAL_SECRET_TOKEN)"
          env:
            - name: JOAL_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.joal.tokenSecret }}
                  key: secret-token
          ports:
            - containerPort: 80
          resources: {{- toYaml .Values.joal.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: joal-config
{{- end }}
