---
# Secret contenant le token secret du WebUI JOAL
apiVersion: v1
kind: Secret
metadata:
  name: joal-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  UI_PATH_PREFIX: "joal"
  UI_SECRET_TOKEN: "osef"
---
