{{- if .Values.joal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: joal
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: joal
  ports:
    - port: 80
      targetPort: 80
{{- end }}
