{{- if .Values.maintainerr.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maintainerr-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.config.storageClass }}
  resources:
    requests:
      storage: {{ .Values.maintainerr.configSize }}
{{- end }}
