kind: Deployment
apiVersion: apps/v1
metadata:
  name: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /usr/src/paperless/data
            - name: media
              mountPath: /usr/src/paperless/media
            - name: export
              mountPath: /usr/src/paperless/export
            - name: consume
              mountPath: /usr/src/paperless/consume
          env:
            - name: PAPERLESS_REDIS
              value: "redis://broker:6379"
            - name: PAPERLESS_DBENGINE
              value: "sqlite"
            - name: PAPERLESS_URL
              value: "https://paperless.ibenyahia.fr"
            - name: PAPERLESS_CSRF_TRUSTED_ORIGINS
              value: "https://paperless.ibenyahia.fr"
          envFrom:
            - secretRef:
                name: paperless-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: media
          persistentVolumeClaim:
            claimName: paperless-media
        - name: export
          persistentVolumeClaim:
            claimName: paperless-export
        - name: consume
          persistentVolumeClaim:
            claimName: paperless-consume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: paperless   # adapte au namespace de ton paperless
  labels:
    app: valkey
spec:
  replicas: 1
  strategy:
    type: Recreate   # évite d'avoir 2 valkey en //  si tu changes de nœud
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:9-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
          volumeMounts:
            - name: valkey-data
              mountPath: /data
          readinessProbe:
            exec:
              command: ["valkey-cli", "ping"]
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["valkey-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: valkey-data
          emptyDir: {}
