apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: PAPERLESS_SECRET_KEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: "paperless-secret-key"
      metadataPolicy: None