apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 5m
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: alertmanager.yaml
    remoteRef:
      key: "alertmanager-config"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: grafana-admin-login
    remoteRef:
      key: "grafana-admin-login"
  - secretKey: grafana-admin-password
    remoteRef:
      key: "grafana-admin-password"