apiVersion: v2
name: iliesflix
description: Stack *arr complète — Sonarr, Radarr, Prowlarr, qBittorrent, Jellyfin, Jellyseerr, Joal, FlareSolverr
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - sonarr
  - radarr
  - jellyfin
  - arr
maintainers:
  - name: ilies
